Use copied env in events (#1186)
* Avoid sharing the request env.

Because Sentry now prepares/sends events in the background, sharing the
same env object with the main thread means that the background worker &
the main thread could process it at the same time. And since env is
essentially a Hash object, this will trigger the

```
RuntimeError: can't add a new key into hash during iteration
```

* Remove ip headers in the Event#rack_env= for explicitness