Copy LICENSE from repository root
Because `rake build` is failed

```
$ bundle exec rake build
rake aborted!
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["LICENSE"] are not files
/Users/sue445/workspace/github.com/getsentry/sentry-ruby/sentry-raven/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/sue445/.rbenv/versions/3.0.0/bin/bundle:23:in `load'
/Users/sue445/.rbenv/versions/3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```